Diploma. Explore-with-me. Statistic service.
NurievLinar/java-explore-with-me pull request #3
Opened 2023-06-13 21:22 UTC by NurievLinar

2023-06-15 10:16 UTC, sergeymamonov requested changes
Не очень хорошая практика называть коммиты одинаковыми названиями.

2023-06-15 10:16 UTC, sergeymamonov commented on ewm-stat-service/pom.xml
> +    <dependencies>
Указывать зависимости в родительском помнике не очень хорошая практика. Лучше указывать все зависимости в дочерних помниках. Пример, нужна зависимость для каждого из подмодулей, но в одном нужна версия 1, а во втором версия 2. Если указывать зависимость в дочерних помниках, то легко указать в одном одну версию, а во втором другую версию.

2023-06-15 10:16 UTC, sergeymamonov commented on ewm-stat-service/stat-client/src/main/java/ru/practicum/ewm/stat/client/StatClient.java
> +}
А где сами методы клиента? Еще нужно написать методы клиента, которые будут отправлять запросы в StatController.

2023-06-15 12:27 UTC, NurievLinar commented on ewm-stat-service/stat-client/src/main/java/ru/practicum/ewm/stat/client/StatClient.java
> +}
Добавил методы.

2023-06-15 12:31 UTC, NurievLinar commented on ewm-stat-service/pom.xml
> +    <dependencies>
Принято. Исправлено.

2023-06-16 03:23 UTC, sergeymamonov approved these changes

2023-06-16 17:11 UTC, merged