Explore-with-me. Main service.
NurievLinar/java-explore-with-me pull request #6
Opened 2023-07-02 20:15 UTC by NurievLinar

2023-07-03 21:18 UTC, sergeymamonov requested changes

2023-07-03 21:18 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +            start = LocalDateTime.now().minusYears(100);
100 лучше вынести в константу.

2023-07-03 21:18 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +}
Лучше добавить обработку RuntimeException.

2023-07-03 21:18 UTC, sergeymamonov commented on ewm-main-service/src/main/resources/schema.sql
> +    name                VARCHAR UNIQUE,
В скриптах sql размер varchar должен быть ограничен.

2023-07-03 21:18 UTC, sergeymamonov commented on ewm-main-service/src/main/resources/schema.sql
> +CREATE INDEX users_email_idx ON USERS(email);
А есть где-то запрос поиска по email? Если такого запроса нет, то и индекс такой не нужен. Он наоборот будет только замедлять запись, так как при записи индекс перестраивается, то есть на это тратиться время.

2023-07-03 21:18 UTC, sergeymamonov commented on ewm-main-service/src/main/resources/schema.sql
> +CREATE INDEX EVENTS_event_date_idx ON EVENTS (event_date);
Для информации, для больших диапазонов, может так быть, что этот индекс тоже не будет работать, то есть это уже определяется на работающей БД или тестовой, но с данными, приближенными к проду. Смотрится план запроса, будет ли использоваться или нет этот индекс. Это уже определяет анализатор исходя из того, как быстрее выполнить запрос, используя индекс или последовательным сканированием.

2023-07-04 18:50 UTC, NurievLinar commented on ewm-main-service/src/main/resources/schema.sql
> +    name                VARCHAR UNIQUE,
Исправлено

2023-07-04 18:57 UTC, NurievLinar commented on ewm-main-service/src/main/resources/schema.sql
> +CREATE INDEX users_email_idx ON USERS(email);
Удалил

2023-07-04 18:58 UTC, NurievLinar commented on ewm-main-service/src/main/resources/schema.sql
> +CREATE INDEX EVENTS_event_date_idx ON EVENTS (event_date);
Исправлено.

2023-07-04 19:06 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +        if (nowDateTime.plusHours(2).isAfter(dtoDateTime)) {
Исправлено

2023-07-04 19:07 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +            start = LocalDateTime.now().minusYears(100);
Исправлено

2023-07-04 19:17 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +        if (!(event.getState().equals(State.CANCELED) || event.getState().equals(State.PENDING))) {
Исправлено.

2023-07-04 19:47 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        } catch (Exception e) {
Понял. Исправлено.

2023-07-04 20:27 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +                switch (Sort.valueOf(sort)) {
Исправлено.

2023-07-04 20:27 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +                switch (Sort.valueOf(sort)) {
Исправлено.

2023-07-04 22:00 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +                .map(eventsRepository::findAllById)
Исправлено.

2023-07-04 22:01 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +                switch (Sort.valueOf(sort)) {
Исправлено.

2023-07-05 20:02 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsService.java
> +    List<EventsShortDto> getEventsWithFilters(String text, List<Long> categories, Boolean paid, LocalDateTime rangeStart,
Спасибо за совет. Можно пока так оставлю?

2023-07-05 20:02 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +                Request request = requestRepository.findById(requestId)
Исправлено.

2023-07-05 20:03 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventsServiceImpl.java
> +            Request request = requestRepository.findById(dto.getRequestIds().get(i))
Исправлено.

2023-07-05 20:52 UTC, NurievLinar commented on ewm-main-service/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +}
Добавил.

2023-07-06 05:00 UTC, sergeymamonov commented on ewm-main-service/src/main/resources/schema.sql
> +CREATE INDEX EVENTS_event_date_idx ON EVENTS (event_date);
Индексы вещь полезная и часто используемая, и знать про них нужно, но использовать их нужно правильно, чтобы они работали.

2023-07-06 05:00 UTC, sergeymamonov approved these changes

2023-07-07 01:01 UTC, merged